import type { Metadata } from 'next'

import './globals.css'

export const metadata: Metadata = {
  title: 'Siminvintory',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossOrigin="anonymous" referrerPolicy="no-referrer" />      
        {/* <link rel="icon" href="/favicon.png" sizes="any" /> */}
      </head>
      <body className={ "bg-[#E9EDF5]"}>{children}</body>
    </html>
  )
}
